name: lint

on: push

jobs:
  lint:
    name: Lint project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: npm install

      - name: Run lint
        run: make lint
